language: "ko-KR"

reviews:
  profile: "chill"
  high_level_summary: true
  review_status: true
  collapse_walkthrough: true
  request_changes_workflow: true
  auto_review:
    enabled: true
    drafts: true

git:
  ignore_branches:
    - "main"
    - "release/*"
